/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Database.MyDatabase;
import Project.Mahasiswa;
import Project.Main;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author ACER
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        HomePanel.setVisible(true);
        ManagePanel.setVisible(false);
        MyDatabase.search_mahasiswa("");
        display_home();
        txtSearchHome.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MainContent = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtSearchHome = new javax.swing.JTextField();
        lblSearchHome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHome = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ManageMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableManage = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSearchManage = new javax.swing.JTextField();
        lblSearchManage = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ManagePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblManage = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblNIM = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbFakultas = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        IPK = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        cbProdi = new javax.swing.JComboBox<>();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        SideBar = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(232, 240, 242));
        MainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 55, 66), 2, true));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainContent.setBackground(new java.awt.Color(232, 240, 242));
        MainContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 55, 66), 2));
        MainContent.setLayout(new java.awt.CardLayout());

        HomePanel.setOpaque(false);
        HomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(232, 240, 242));
        jLabel11.setFont(new java.awt.Font("Futura Md BT", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(5, 55, 66));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Home Page");
        HomePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 636, 40));

        txtSearchHome.setBackground(new java.awt.Color(232, 240, 242));
        txtSearchHome.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        txtSearchHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSearchHome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchHomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchHomeFocusLost(evt);
            }
        });
        txtSearchHome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchHomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchHomeKeyTyped(evt);
            }
        });
        HomePanel.add(txtSearchHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 68, 600, 30));

        lblSearchHome.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        lblSearchHome.setForeground(new java.awt.Color(5, 55, 66));
        lblSearchHome.setText("____________________________________________________________________________________________________");
        lblSearchHome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        HomePanel.add(lblSearchHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, -1, 30));

        tableHome.setBackground(new java.awt.Color(202, 235, 252));
        tableHome.setFont(new java.awt.Font("Futura Md BT", 0, 13)); // NOI18N
        tableHome.setForeground(new java.awt.Color(5, 55, 66));
        tableHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableHome.setGridColor(new java.awt.Color(5, 55, 66));
        tableHome.setRowHeight(25);
        tableHome.setSelectionBackground(new java.awt.Color(57, 162, 219));
        tableHome.setSelectionForeground(new java.awt.Color(232, 240, 242));
        tableHome.getTableHeader().setResizingAllowed(false);
        tableHome.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableHome);

        HomePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 124, 636, 276));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/search.png"))); // NOI18N
        HomePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 68, -1, -1));

        MainContent.add(HomePanel, "card2");

        ManageMain.setOpaque(false);
        ManageMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableManage.setBackground(new java.awt.Color(202, 235, 252));
        tableManage.setFont(new java.awt.Font("Futura Md BT", 0, 13)); // NOI18N
        tableManage.setForeground(new java.awt.Color(5, 55, 66));
        tableManage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableManage.setGridColor(new java.awt.Color(5, 55, 66));
        tableManage.setRowHeight(25);
        tableManage.setSelectionBackground(new java.awt.Color(57, 162, 219));
        tableManage.setSelectionForeground(new java.awt.Color(232, 240, 242));
        tableManage.getTableHeader().setResizingAllowed(false);
        tableManage.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableManage);

        ManageMain.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, 664, 276));

        btnTambah.setBackground(new java.awt.Color(57, 162, 219));
        btnTambah.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(232, 240, 242));
        btnTambah.setText("Add");
        btnTambah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 162, 219), 2, true));
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        ManageMain.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 80, 35));

        btnUpdate.setBackground(new java.awt.Color(57, 162, 219));
        btnUpdate.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(232, 240, 242));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 162, 219), 2, true));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        ManageMain.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 83, 80, 35));

        btnDelete.setBackground(new java.awt.Color(57, 162, 219));
        btnDelete.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(232, 240, 242));
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 162, 219), 2, true));
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        ManageMain.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 83, 80, 35));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/search.png"))); // NOI18N
        ManageMain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 85, -1, -1));

        txtSearchManage.setBackground(new java.awt.Color(232, 240, 242));
        txtSearchManage.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        txtSearchManage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSearchManage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchManageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchManageFocusLost(evt);
            }
        });
        txtSearchManage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchManageKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchManageKeyTyped(evt);
            }
        });
        ManageMain.add(txtSearchManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 210, 23));

        lblSearchManage.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        lblSearchManage.setForeground(new java.awt.Color(5, 55, 66));
        lblSearchManage.setText("___________________________________");
        lblSearchManage.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ManageMain.add(lblSearchManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 210, 20));

        jLabel13.setBackground(new java.awt.Color(232, 240, 242));
        jLabel13.setFont(new java.awt.Font("Futura Md BT", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(5, 55, 66));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Manage Data Mahasiswa");
        ManageMain.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, 636, 40));

        MainContent.add(ManageMain, "card4");

        ManagePanel.setBackground(new java.awt.Color(255, 255, 255));
        ManagePanel.setOpaque(false);

        jLabel4.setBackground(new java.awt.Color(232, 240, 242));
        jLabel4.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 55, 66));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nama Lengkap");

        lblManage.setBackground(new java.awt.Color(232, 240, 242));
        lblManage.setFont(new java.awt.Font("Futura Md BT", 1, 16)); // NOI18N
        lblManage.setForeground(new java.awt.Color(5, 55, 66));
        lblManage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManage.setText("Tambah Data Mahasiswa");

        txtNama.setBackground(new java.awt.Color(232, 240, 242));
        txtNama.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        txtNama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaFocusLost(evt);
            }
        });
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        lblNama.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        lblNama.setForeground(new java.awt.Color(5, 55, 66));
        lblNama.setText("__________________________________________________");
        lblNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtNim.setBackground(new java.awt.Color(232, 240, 242));
        txtNim.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        txtNim.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNimFocusLost(evt);
            }
        });
        txtNim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNimKeyTyped(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(232, 240, 242));
        jLabel6.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(5, 55, 66));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NIM");

        lblNIM.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        lblNIM.setForeground(new java.awt.Color(5, 55, 66));
        lblNIM.setText("__________________________________________________");
        lblNIM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel7.setBackground(new java.awt.Color(232, 240, 242));
        jLabel7.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(5, 55, 66));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jenis Kelamin");

        jLabel8.setBackground(new java.awt.Color(232, 240, 242));
        jLabel8.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(5, 55, 66));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("IPK");

        cbFakultas.setBackground(new java.awt.Color(162, 219, 250));
        cbFakultas.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        cbFakultas.setForeground(new java.awt.Color(5, 55, 66));
        cbFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "FEB", "FISIP", "FAPERTA", "FAHUTAN", "FKIP", "FPIK", "FMIPA", "FH", "FT", "FK", "FKM", "FFARM", "FIB" }));
        cbFakultas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 55, 66)));
        cbFakultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbFakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFakultasActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(232, 240, 242));
        jLabel9.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(5, 55, 66));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fakultas");

        IPK.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        IPK.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 4.0d, 0.1d));
        IPK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 55, 66)));
        IPK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setBackground(new java.awt.Color(232, 240, 242));
        jLabel10.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(5, 55, 66));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Program Studi");

        cbProdi.setBackground(new java.awt.Color(162, 219, 250));
        cbProdi.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        cbProdi.setForeground(new java.awt.Color(5, 55, 66));
        cbProdi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 55, 66)));
        cbProdi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbProdi.setEnabled(false);

        rbLaki.setBackground(new java.awt.Color(232, 240, 242));
        rbLaki.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        rbLaki.setForeground(new java.awt.Color(5, 55, 66));
        rbLaki.setText("Laki-laki");
        rbLaki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });

        rbPerempuan.setBackground(new java.awt.Color(232, 240, 242));
        rbPerempuan.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        rbPerempuan.setForeground(new java.awt.Color(5, 55, 66));
        rbPerempuan.setText("Perempuan");
        rbPerempuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(57, 162, 219));
        btnSave.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(232, 240, 242));
        btnSave.setText("Simpan");
        btnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 162, 219), 2, true));
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(57, 162, 219));
        btnClear.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(232, 240, 242));
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 162, 219), 2, true));
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(232, 240, 242));
        btnBack.setFont(new java.awt.Font("Futura Md BT", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(232, 240, 242));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagePanelLayout = new javax.swing.GroupLayout(ManagePanel);
        ManagePanel.setLayout(ManagePanelLayout);
        ManagePanelLayout.setHorizontalGroup(
            ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(ManagePanelLayout.createSequentialGroup()
                        .addComponent(rbLaki)
                        .addGap(61, 61, 61)
                        .addComponent(rbPerempuan))
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ManagePanelLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(IPK)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagePanelLayout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManage, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        ManagePanelLayout.setVerticalGroup(
            ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagePanelLayout.createSequentialGroup()
                .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblManage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ManagePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManagePanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ManagePanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagePanelLayout.createSequentialGroup()
                        .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbLaki)
                            .addComponent(rbPerempuan))
                        .addGap(30, 30, 30)
                        .addGroup(ManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(IPK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        MainContent.add(ManagePanel, "card3");

        MainPanel.add(MainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 680, 410));

        SideBar.setBackground(new java.awt.Color(57, 162, 219));
        SideBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 55, 66), 2));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(57, 162, 219));
        btnHome.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(232, 240, 242));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/home.png"))); // NOI18N
        btnHome.setText("  Home");
        btnHome.setBorder(null);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHideActionText(true);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        SideBar.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 130, 115, 45));

        btnLogout.setBackground(new java.awt.Color(57, 162, 219));
        btnLogout.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(232, 240, 242));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/exit.png"))); // NOI18N
        btnLogout.setText("  Logout");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        SideBar.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 368, 115, 40));

        btnManage.setBackground(new java.awt.Color(57, 162, 219));
        btnManage.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnManage.setForeground(new java.awt.Color(232, 240, 242));
        btnManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/manage.png"))); // NOI18N
        btnManage.setText("  Manage");
        btnManage.setBorder(null);
        btnManage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManage.setHideActionText(true);
        btnManage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageMouseExited(evt);
            }
        });
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        SideBar.add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 175, 115, 45));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logo.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SideBar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 3, 110, 115));

        MainPanel.add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 410));

        Header.setBackground(new java.awt.Color(5, 55, 66));

        jLabel2.setBackground(new java.awt.Color(232, 240, 242));
        jLabel2.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 240, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aplikasi Pendataan Mahasiswa");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainPanel.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private String crud;
    private int NIM;
    
    private void generate_prodi(int fakultas){
        cbProdi.removeAllItems();
        if (fakultas == 1){
            cbProdi.addItem("Akuntansi");
            cbProdi.addItem("Ilmu Ekonomi");
            cbProdi.addItem("Manajemen");
            cbProdi.addItem("Ekonomi Pembangunan");
            cbProdi.addItem("Ekonomi Islam");
            cbProdi.addItem("Profesi Akuntan");
        } else if (fakultas == 2){
            cbProdi.addItem("Ilmu Administrasi Bisnis");
            cbProdi.addItem("Ilmu Administrasi Negara");
            cbProdi.addItem("Ilmu Pemerintahan");
            cbProdi.addItem("Ilmu Hubungan Internasional");
            cbProdi.addItem("Pemerintah Integratif");
            cbProdi.addItem("Ilmu Komunikasi");
            cbProdi.addItem("Ilmu Sosiatri");
            cbProdi.addItem("Psikologi");      
        } else if (fakultas == 3){
            cbProdi.addItem("Agroekoteknologi");
            cbProdi.addItem("Agribisnis");
            cbProdi.addItem("Teknologi Hasil Pertanian");
            cbProdi.addItem("Peternakan");
            cbProdi.addItem("Pertanian Tropika Basah");
        } else if (fakultas == 4){
            cbProdi.addItem("Ilmu Kehutanan");
        } else if (fakultas == 5) {
            cbProdi.addItem("Pendidikan Matematika");
            cbProdi.addItem("Pendidikan Fisika");
            cbProdi.addItem("Pendidikan Kimia");
            cbProdi.addItem("Pendidikan Biologi");
            cbProdi.addItem("Pendidikan Jasmani, Kesehatan dan Rekreas");
            cbProdi.addItem("Bimbingan dan Konseling");
            cbProdi.addItem("Pendidikan Luar Sekolah");
            cbProdi.addItem("Pendidikan Guru Sekolah Dasar");
            cbProdi.addItem("Pendidikan Guru Pendidikan Anak Usia Dini");
            cbProdi.addItem("Pendidikan Ekonomi");
            cbProdi.addItem("Pendidikan Pancasila dan Kewarganegaraan");
            cbProdi.addItem("Pendidikan Bahasa dan Sastra Indonesia");
            cbProdi.addItem("Pendidikan Bahasa Inggris");
            cbProdi.addItem("Pendidikan Geografi");
            cbProdi.addItem("Pendidikan Sejarah");
            cbProdi.addItem("Pendidikan Komputer");
            cbProdi.addItem("Pendidikan Profesi Guru SD");
            cbProdi.addItem("Pendidikan Profesi Guru");       
        } else if (fakultas == 6){
            cbProdi.addItem("Budidaya Perairan");
            cbProdi.addItem("Manajemen Sumberdaya Perairan");
            cbProdi.addItem("Agrobisnis Perikanan");
            cbProdi.addItem("Teknologi Hasil Perikanan");
            cbProdi.addItem("Peternakan");
        } else if (fakultas == 7){            cbProdi.addItem("Ilmu Kelautan");
            cbProdi.addItem("Jurusan Biologi");
            cbProdi.addItem("Jurusan Kimia");
            cbProdi.addItem("Jurusan Fisika");
            cbProdi.addItem("Jurusan Matematika");
            cbProdi.addItem("Jurusan Statistika");
            cbProdi.addItem("Jurusan Geofisika");
        } else if (fakultas == 8){
            cbProdi.addItem("Ilmu Hukum");
        } else if (fakultas == 9){
            cbProdi.addItem("Teknik Pertambangan");
            cbProdi.addItem("Teknik Industri");
            cbProdi.addItem("Teknik Sipil");
            cbProdi.addItem("Teknik Kimia");
            cbProdi.addItem("Teknik Lingkungan");
            cbProdi.addItem("Teknik Elektro");
            cbProdi.addItem("Teknik Geologi");
            cbProdi.addItem("Teknik Mesin");
            cbProdi.addItem("Arsitektur");
            cbProdi.addItem("Informatika");
            cbProdi.addItem("Sistem Informasi");      
        } else if (fakultas == 10){
            cbProdi.addItem("Pendidikan Dokter");
            cbProdi.addItem("Kedokteran Gigi");
            cbProdi.addItem("Keperawatan");
            cbProdi.addItem("Spesialis Bedah");
        } else if (fakultas == 11){
            cbProdi.addItem("Ilmu Kesehatan Masyarakat");
        } else if (fakultas == 12){
            cbProdi.addItem("Farmasi");
            cbProdi.addItem("Farmasi Klinis");
        } else if (fakultas == 13){
            cbProdi.addItem("Sastra Indonesia");
            cbProdi.addItem("Sastra Ingris");
            cbProdi.addItem("Etnomusikologi");
        }
    }
    
    private boolean cek_input(){
        if (txtNama.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Kolom Nama Harus Diisi!", "Warning!", JOptionPane.WARNING_MESSAGE);
            txtNama.requestFocus();
            return false;
        } else if (txtNim.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Kolom NIM Harus Diisi!", "Warning!", JOptionPane.WARNING_MESSAGE);
            txtNim.requestFocus();
            return false;
        } else if (!rbLaki.isSelected() && !rbPerempuan.isSelected()){
            JOptionPane.showMessageDialog(this, "Jenis Kelamin Harus Dipilih!", "Warning!", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (cbFakultas.getSelectedIndex() < 1){
            JOptionPane.showMessageDialog(this, "Kolom Fakultas Harus Dipilih!", "Warning!", JOptionPane.WARNING_MESSAGE);
            cbFakultas.requestFocus();
            return false;
        } else if (IPK.getValue().equals(0)){
            JOptionPane.showMessageDialog(this, "Kolom IPK Harus Diisi!", "Warning!", JOptionPane.WARNING_MESSAGE);
            IPK.requestFocus();
            return false;
        }
        int nim;
        double ipk;
        try {
            nim = Integer.parseInt(txtNim.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "NIM Harus Berupa Angka!", "Warning!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            ipk = Double.parseDouble(IPK.getValue().toString());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "IPK Harus Berupa Angka Dari 0.1 sampai 4!", "Warning!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (ipk <= 0 || ipk > 4){
            JOptionPane.showMessageDialog(this, "IPK Harus Berupa Angka Dari 0.1 sampai 4!", "Warning!", JOptionPane.WARNING_MESSAGE);
            IPK.requestFocus();
            return false;
        }
        return true;
    }
    
    private void cls(){
        txtNama.setText("");
        txtNim.setText("");
        rbLaki.setSelected(false);
        rbPerempuan.setSelected(false);
        cbFakultas.setSelectedIndex(0);
        cbProdi.removeAllItems();
        cbProdi.setEnabled(false);
        IPK.setValue(0);
        txtSearchHome.setText("");
        txtSearchManage.setText("");
        txtNama.requestFocus();
    }
    
    private void display(String search){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("NIM");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Fakultas");
        model.addColumn("Prodi");
        model.addColumn("IPK");
        
        if (search.equalsIgnoreCase("")){
            for (int i = 0 ; i < Main.dataMahasiswa.size() ; i++){
                model.addRow(new Object[] {(i+1), Main.dataMahasiswa.get(i).getNim(), Main.dataMahasiswa.get(i).getNama(), 
                                            Main.dataMahasiswa.get(i).getJK(), Main.dataMahasiswa.get(i).getFakultas(), 
                                            Main.dataMahasiswa.get(i).getProdi(), Main.dataMahasiswa.get(i).getIpk()});
            }
        } else {
            MyDatabase.search_mahasiswa(search);
            for (int i = 0 ; i < Main.dataSearch.size() ; i++){
                model.addRow(new Object[] {(i+1), Main.dataSearch.get(i).getNim(), Main.dataSearch.get(i).getNama(), 
                                            Main.dataSearch.get(i).getJK(), Main.dataSearch.get(i).getFakultas(), 
                                            Main.dataSearch.get(i).getProdi(), Main.dataSearch.get(i).getIpk()});
            }
            
        }
        
        tableManage.setModel(model);
        tableManage.getColumnModel().getColumn(0).setPreferredWidth(1);
        tableManage.getColumnModel().getColumn(1).setPreferredWidth(50);
        tableManage.getColumnModel().getColumn(2).setPreferredWidth(50);
        tableManage.getColumnModel().getColumn(3).setPreferredWidth(45);
        tableManage.getColumnModel().getColumn(4).setPreferredWidth(25);
        tableManage.getColumnModel().getColumn(5).setPreferredWidth(120);
        tableManage.getColumnModel().getColumn(6).setPreferredWidth(5);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TableColumnModel columnModel = tableManage.getColumnModel();
        for (int i = 0 ; i < 7 ; i++){
            columnModel.getColumn(i).setCellRenderer(centerRenderer);
        }
//        agar isi table tidak dapat diedit
        tableManage.setDefaultEditor(Object.class, null);
    }
    
    public void display_home(){;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIM");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Fakultas");
        model.addColumn("Prodi");
        model.addColumn("IPK");
        
        for (int i = 0 ; i < Main.dataSearch.size() ; i++){
            model.addRow(new Object[] {Main.dataSearch.get(i).getNim(), Main.dataSearch.get(i).getNama(), 
                                        Main.dataSearch.get(i).getJK(), Main.dataSearch.get(i).getFakultas(), 
                                        Main.dataSearch.get(i).getProdi(), Main.dataSearch.get(i).getIpk()});
        }
        
        tableHome.setModel(model);
        tableHome.getColumnModel().getColumn(0).setPreferredWidth(50);
        tableHome.getColumnModel().getColumn(1).setPreferredWidth(50);
        tableHome.getColumnModel().getColumn(2).setPreferredWidth(45);
        tableHome.getColumnModel().getColumn(3).setPreferredWidth(25);
        tableHome.getColumnModel().getColumn(4).setPreferredWidth(120);
        tableHome.getColumnModel().getColumn(5).setPreferredWidth(5);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TableColumnModel columnModel = tableHome.getColumnModel();
        for (int i = 0 ; i < 6 ; i++){
            columnModel.getColumn(i).setCellRenderer(centerRenderer);
        }
//        agar isi table tidak dapat diedit
        tableHome.setDefaultEditor(Object.class, null);
    }
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        ManagePanel.setVisible(false);
        ManageMain.setVisible(false);
        HomePanel.setVisible(true);
        MyDatabase.search_mahasiswa("");
        display_home();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        ManageMain.setVisible(true);
        ManagePanel.setVisible(false);
        HomePanel.setVisible(false);
        display("");
        cls();
        txtSearchManage.requestFocus();
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        Color color1 = Color.decode("#fc5347");
        btnLogout.setBackground(color1);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        Color color1 = Color.decode("#39A2DB");
        btnLogout.setBackground(color1);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color color1 = Color.decode("#A2DBFA");
        btnHome.setBackground(color1);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color color1 = Color.decode("#39A2DB");
        btnHome.setBackground(color1);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnManageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMouseEntered
        Color color1 = Color.decode("#A2DBFA");
        btnManage.setBackground(color1);
    }//GEN-LAST:event_btnManageMouseEntered

    private void btnManageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMouseExited
        Color color1 = Color.decode("#39A2DB");
        btnManage.setBackground(color1);
    }//GEN-LAST:event_btnManageMouseExited

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        Color color1 = Color.decode("#39A2DB");
        lblNama.setForeground(color1);
    }//GEN-LAST:event_txtNamaFocusGained

    private void txtNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusLost
        Color color1 = Color.decode("#053742");
        lblNama.setForeground(color1);
    }//GEN-LAST:event_txtNamaFocusLost

    private void txtNimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNimFocusGained
        Color color1 = Color.decode("#39A2DB");
        lblNIM.setForeground(color1);
    }//GEN-LAST:event_txtNimFocusGained

    private void txtNimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNimFocusLost
        Color color1 = Color.decode("#053742");
        lblNIM.setForeground(color1);
    }//GEN-LAST:event_txtNimFocusLost

    private void cbFakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFakultasActionPerformed
        if (cbFakultas.getSelectedIndex() > 0){
            cbProdi.setEnabled(true);
            generate_prodi(cbFakultas.getSelectedIndex());
        } else {
            cbProdi.removeAllItems();
            cbProdi.setEnabled(false);
        }
    }//GEN-LAST:event_cbFakultasActionPerformed

    private void rbPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanActionPerformed
        if (rbPerempuan.isSelected()){
            rbLaki.setSelected(false);
        }
    }//GEN-LAST:event_rbPerempuanActionPerformed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        Color color1 = Color.decode("#E8F0F2");
        Color color2 = Color.decode("#053742");
        btnSave.setBackground(color1);
        btnSave.setForeground(color2);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        Color color1 = Color.decode("#39A2DB");
        Color color2 = Color.decode("#E8F0F2");
        btnSave.setBackground(color1);
        btnSave.setForeground(color2);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (cek_input()){
            String nama = txtNama.getText();
            String jk;
            if (rbLaki.isSelected()){
                jk = rbLaki.getText();
            } else {
                jk = rbPerempuan.getText();
            }
            String fakultas = cbFakultas.getSelectedItem().toString();
            String prodi = cbProdi.getSelectedItem().toString();
            int nim = Integer.parseInt(txtNim.getText());
            double ipk = Double.parseDouble(IPK.getValue().toString());
            if (crud.equalsIgnoreCase("c")){
                if (Main.cek_nim(nim)){
                    MyDatabase.insert_mahasiswa(nama, jk, fakultas, prodi, nim, ipk);
                    Mahasiswa newMhs = new Mahasiswa(nama, nim, jk, fakultas, prodi, ipk);
                    Main.dataMahasiswa.add(newMhs);
                    NIM = nim;
                    JOptionPane.showMessageDialog(this, "Berhasil Menambah Data Mahasiswa!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "NIM Telah Terdaftar!", "Warning!", JOptionPane.WARNING_MESSAGE);
                    txtNim.requestFocus();
                }
            } else {
                if (Main.cek_nim(nim) || nim == NIM){
                    MyDatabase.update_mahasiswa(NIM, nim, nama, jk, fakultas, prodi, ipk);
                    MyDatabase.read_mahasiswa();
                    JOptionPane.showMessageDialog(this, "Berhasil Update Data Mahasiswa!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "NIM Telah Terdaftar!", "Warning!", JOptionPane.WARNING_MESSAGE);
                    txtNim.requestFocus();
                }
            }
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        if (rbLaki.isSelected()){
            rbPerempuan.setSelected(false);
        }
    }//GEN-LAST:event_rbLakiActionPerformed

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        Color color1 = Color.decode("#E8F0F2");
        Color color2 = Color.decode("#053742");
        btnClear.setBackground(color1);
        btnClear.setForeground(color2);
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        Color color1 = Color.decode("#39A2DB");
        Color color2 = Color.decode("#E8F0F2");
        btnClear.setBackground(color1);
        btnClear.setForeground(color2);
    }//GEN-LAST:event_btnClearMouseExited

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cls();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtSearchHomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchHomeFocusLost
        Color color1 = Color.decode("#053742");
        lblSearchHome.setForeground(color1);
    }//GEN-LAST:event_txtSearchHomeFocusLost

    private void txtSearchHomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchHomeFocusGained
        Color color1 = Color.decode("#39A2DB");
        lblSearchHome.setForeground(color1);
    }//GEN-LAST:event_txtSearchHomeFocusGained

    private void txtSearchHomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchHomeKeyReleased
        if (txtSearchHome.getText().equalsIgnoreCase("")){
            MyDatabase.search_mahasiswa("");
        } else {
            MyDatabase.search_mahasiswa(txtSearchHome.getText());
        }
        display_home();
    }//GEN-LAST:event_txtSearchHomeKeyReleased

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        Color color1 = Color.decode("#E8F0F2");
        Color color2 = Color.decode("#053742");
        btnTambah.setBackground(color1);
        btnTambah.setForeground(color2);
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        Color color1 = Color.decode("#39A2DB");
        Color color2 = Color.decode("#E8F0F2");
        btnTambah.setBackground(color1);
        btnTambah.setForeground(color2);
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        crud = "c";
        lblManage.setText("Tambah Data Mahasiswa");
        ManageMain.setVisible(false);
        ManagePanel.setVisible(true);
        HomePanel.setVisible(false);
        cls();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        Color color1 = Color.decode("#E8F0F2");
        Color color2 = Color.decode("#053742");
        btnUpdate.setBackground(color1);
        btnUpdate.setForeground(color2);
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        Color color1 = Color.decode("#39A2DB");
        Color color2 = Color.decode("#E8F0F2");
        btnUpdate.setBackground(color1);
        btnUpdate.setForeground(color2);
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tableManage.getSelectedRow();
        if (selectedRow != -1){
            NIM = Integer.parseInt(tableManage.getValueAt(selectedRow, 1).toString());
            txtNim.setText(tableManage.getValueAt(selectedRow, 1).toString());
            txtNama.setText(tableManage.getValueAt(selectedRow, 2).toString());
            if (tableManage.getValueAt(selectedRow, 3).toString().equalsIgnoreCase("Laki-laki")){
                rbLaki.setSelected(true);
                rbPerempuan.setSelected(false);
            } else {
                rbPerempuan.setSelected(true);
                rbLaki.setSelected(false);
            }
            cbFakultas.setSelectedItem(tableManage.getValueAt(selectedRow, 4).toString());
            cbProdi.setEnabled(true);
            generate_prodi(cbFakultas.getSelectedIndex());
            
            cbProdi.setSelectedItem(tableManage.getValueAt(selectedRow, 5).toString());
            IPK.setValue(Double.valueOf(tableManage.getValueAt(selectedRow, 6).toString()));
   
            crud = "u";
            lblManage.setText("Update Data Mahasiswa");
            ManageMain.setVisible(false);
            ManagePanel.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Mahasiswa Yang Ingin Diupdate Terlebih Dahulu!", "Warning!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        Color color1 = Color.decode("#E8F0F2");
        Color color2 = Color.decode("#053742");
        btnDelete.setBackground(color1);
        btnDelete.setForeground(color2);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        Color color1 = Color.decode("#39A2DB");
        Color color2 = Color.decode("#E8F0F2");
        btnDelete.setBackground(color1);
        btnDelete.setForeground(color2);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tableManage.getSelectedRow();
        if (selectedRow != -1){
            int nim = Integer.parseInt(tableManage.getValueAt(selectedRow, 1).toString());
            int pilih = JOptionPane.showConfirmDialog(null, "Apakah yakin Ingin Menghapus Data Mahasiswa Dengan NIM "+ nim +"?", "Question", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (pilih == JOptionPane.YES_OPTION){
                MyDatabase.delete_mahasiswa(nim);
                MyDatabase.read_mahasiswa();
                txtSearchManage.setText("");
                display("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Mahasiswa Yang Ingin Dihapus Terlebih Dahulu!", "Warning!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchManageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchManageFocusGained
        Color color1 = Color.decode("#39A2DB");
        lblSearchManage.setForeground(color1);
    }//GEN-LAST:event_txtSearchManageFocusGained

    private void txtSearchManageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchManageFocusLost
        Color color1 = Color.decode("#053742");
        lblSearchManage.setForeground(color1);
    }//GEN-LAST:event_txtSearchManageFocusLost

    private void txtSearchManageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchManageKeyReleased
        display(txtSearchManage.getText());
    }//GEN-LAST:event_txtSearchManageKeyReleased

    private void txtSearchHomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchHomeKeyTyped
        if (txtSearchHome.getText().length() >= 30 ){
            evt.consume();
        }  
    }//GEN-LAST:event_txtSearchHomeKeyTyped

    private void txtSearchManageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchManageKeyTyped
        if (txtSearchManage.getText().length() >= 30 ){
            evt.consume();
        }  
    }//GEN-LAST:event_txtSearchManageKeyTyped

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        if (txtNama.getText().length() >= 30 ){
            evt.consume();
        }  
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtNimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNimKeyTyped
        if (txtNim.getText().length() >= 30 ){
            evt.consume();
        }  
    }//GEN-LAST:event_txtNimKeyTyped

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        Color color1 = Color.decode("#fc5347");
        btnBack.setBackground(color1);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        Color color1 = Color.decode("#E8F0F2");
        btnBack.setBackground(color1);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ManageMain.setVisible(true);
        ManagePanel.setVisible(false);
        HomePanel.setVisible(false);
        display("");
        cls();
        txtSearchManage.requestFocus();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JSpinner IPK;
    private javax.swing.JPanel MainContent;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel ManageMain;
    private javax.swing.JPanel ManagePanel;
    private javax.swing.JPanel SideBar;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbFakultas;
    private javax.swing.JComboBox<String> cbProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblManage;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblSearchHome;
    private javax.swing.JLabel lblSearchManage;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tableHome;
    private javax.swing.JTable tableManage;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtSearchHome;
    private javax.swing.JTextField txtSearchManage;
    // End of variables declaration//GEN-END:variables
}
